// Comprehensive list of all countries with ISD codes, flags, and names
// Sorted by ISD code numerically

export interface CountryData {
  code: string;
  name: string;
  isd: string;
  flag: string;
}

export const ALL_COUNTRIES: CountryData[] = [
  { code: "US", name: "United States", isd: "+1", flag: "🇺🇸" },
  { code: "CA", name: "Canada", isd: "+1", flag: "🇨🇦" },
  { code: "EG", name: "Egypt", isd: "+20", flag: "🇪🇬" },
  { code: "ZA", name: "South Africa", isd: "+27", flag: "🇿🇦" },
  { code: "GR", name: "Greece", isd: "+30", flag: "🇬🇷" },
  { code: "NL", name: "Netherlands", isd: "+31", flag: "🇳🇱" },
  { code: "BE", name: "Belgium", isd: "+32", flag: "🇧🇪" },
  { code: "FR", name: "France", isd: "+33", flag: "🇫🇷" },
  { code: "ES", name: "Spain", isd: "+34", flag: "🇪🇸" },
  { code: "HU", name: "Hungary", isd: "+36", flag: "🇭🇺" },
  { code: "IT", name: "Italy", isd: "+39", flag: "🇮🇹" },
  { code: "RO", name: "Romania", isd: "+40", flag: "🇷🇴" },
  { code: "CH", name: "Switzerland", isd: "+41", flag: "🇨🇭" },
  { code: "AT", name: "Austria", isd: "+43", flag: "🇦🇹" },
  { code: "GB", name: "United Kingdom", isd: "+44", flag: "🇬🇧" },
  { code: "DK", name: "Denmark", isd: "+45", flag: "🇩🇰" },
  { code: "SE", name: "Sweden", isd: "+46", flag: "🇸🇪" },
  { code: "NO", name: "Norway", isd: "+47", flag: "🇳🇴" },
  { code: "PL", name: "Poland", isd: "+48", flag: "🇵🇱" },
  { code: "DE", name: "Germany", isd: "+49", flag: "🇩🇪" },
  { code: "PE", name: "Peru", isd: "+51", flag: "🇵🇪" },
  { code: "MX", name: "Mexico", isd: "+52", flag: "🇲🇽" },
  { code: "CU", name: "Cuba", isd: "+53", flag: "🇨🇺" },
  { code: "AR", name: "Argentina", isd: "+54", flag: "🇦🇷" },
  { code: "BR", name: "Brazil", isd: "+55", flag: "🇧🇷" },
  { code: "CL", name: "Chile", isd: "+56", flag: "🇨🇱" },
  { code: "CO", name: "Colombia", isd: "+57", flag: "🇨🇴" },
  { code: "VE", name: "Venezuela", isd: "+58", flag: "🇻🇪" },
  { code: "MY", name: "Malaysia", isd: "+60", flag: "🇲🇾" },
  { code: "AU", name: "Australia", isd: "+61", flag: "🇦🇺" },
  { code: "ID", name: "Indonesia", isd: "+62", flag: "🇮🇩" },
  { code: "PH", name: "Philippines", isd: "+63", flag: "🇵🇭" },
  { code: "NZ", name: "New Zealand", isd: "+64", flag: "🇳🇿" },
  { code: "SG", name: "Singapore", isd: "+65", flag: "🇸🇬" },
  { code: "TH", name: "Thailand", isd: "+66", flag: "🇹🇭" },
  { code: "JP", name: "Japan", isd: "+81", flag: "🇯🇵" },
  { code: "KR", name: "South Korea", isd: "+82", flag: "🇰🇷" },
  { code: "VN", name: "Vietnam", isd: "+84", flag: "🇻🇳" },
  { code: "CN", name: "China", isd: "+86", flag: "🇨🇳" },
  { code: "TR", name: "Turkey", isd: "+90", flag: "🇹🇷" },
  { code: "IN", name: "India", isd: "+91", flag: "🇮🇳" },
  { code: "PK", name: "Pakistan", isd: "+92", flag: "🇵🇰" },
  { code: "AF", name: "Afghanistan", isd: "+93", flag: "🇦🇫" },
  { code: "LK", name: "Sri Lanka", isd: "+94", flag: "🇱🇰" },
  { code: "MM", name: "Myanmar", isd: "+95", flag: "🇲🇲" },
  { code: "IR", name: "Iran", isd: "+98", flag: "🇮🇷" },
  { code: "SS", name: "South Sudan", isd: "+211", flag: "🇸🇸" },
  { code: "MA", name: "Morocco", isd: "+212", flag: "🇲🇦" },
  { code: "DZ", name: "Algeria", isd: "+213", flag: "🇩🇿" },
  { code: "TN", name: "Tunisia", isd: "+216", flag: "🇹🇳" },
  { code: "LY", name: "Libya", isd: "+218", flag: "🇱🇾" },
  { code: "GM", name: "Gambia", isd: "+220", flag: "🇬🇲" },
  { code: "SN", name: "Senegal", isd: "+221", flag: "🇸🇳" },
  { code: "MR", name: "Mauritania", isd: "+222", flag: "🇲🇷" },
  { code: "ML", name: "Mali", isd: "+223", flag: "🇲🇱" },
  { code: "GN", name: "Guinea", isd: "+224", flag: "🇬🇳" },
  { code: "CI", name: "Ivory Coast", isd: "+225", flag: "🇨🇮" },
  { code: "BF", name: "Burkina Faso", isd: "+226", flag: "🇧🇫" },
  { code: "NE", name: "Niger", isd: "+227", flag: "🇳🇪" },
  { code: "TG", name: "Togo", isd: "+228", flag: "🇹🇬" },
  { code: "BJ", name: "Benin", isd: "+229", flag: "🇧🇯" },
  { code: "MU", name: "Mauritius", isd: "+230", flag: "🇲🇺" },
  { code: "LR", name: "Liberia", isd: "+231", flag: "🇱🇷" },
  { code: "SL", name: "Sierra Leone", isd: "+232", flag: "🇸🇱" },
  { code: "GH", name: "Ghana", isd: "+233", flag: "🇬🇭" },
  { code: "NG", name: "Nigeria", isd: "+234", flag: "🇳🇬" },
  { code: "TD", name: "Chad", isd: "+235", flag: "🇹🇩" },
  { code: "CF", name: "Central African Republic", isd: "+236", flag: "🇨🇫" },
  { code: "CM", name: "Cameroon", isd: "+237", flag: "🇨🇲" },
  { code: "CV", name: "Cape Verde", isd: "+238", flag: "🇨🇻" },
  { code: "ST", name: "Sao Tome and Principe", isd: "+239", flag: "🇸🇹" },
  { code: "GQ", name: "Equatorial Guinea", isd: "+240", flag: "🇬🇶" },
  { code: "GA", name: "Gabon", isd: "+241", flag: "🇬🇦" },
  { code: "CG", name: "Republic of the Congo", isd: "+242", flag: "🇨🇬" },
  { code: "CD", name: "Democratic Republic of the Congo", isd: "+243", flag: "🇨🇩" },
  { code: "AO", name: "Angola", isd: "+244", flag: "🇦🇴" },
  { code: "GW", name: "Guinea-Bissau", isd: "+245", flag: "🇬🇼" },
  { code: "SC", name: "Seychelles", isd: "+248", flag: "🇸🇨" },
  { code: "SD", name: "Sudan", isd: "+249", flag: "🇸🇩" },
  { code: "RW", name: "Rwanda", isd: "+250", flag: "🇷🇼" },
  { code: "ET", name: "Ethiopia", isd: "+251", flag: "🇪🇹" },
  { code: "SO", name: "Somalia", isd: "+252", flag: "🇸🇴" },
  { code: "DJ", name: "Djibouti", isd: "+253", flag: "🇩🇯" },
  { code: "KE", name: "Kenya", isd: "+254", flag: "🇰🇪" },
  { code: "TZ", name: "Tanzania", isd: "+255", flag: "🇹🇿" },
  { code: "UG", name: "Uganda", isd: "+256", flag: "🇺🇬" },
  { code: "BI", name: "Burundi", isd: "+257", flag: "🇧🇮" },
  { code: "MZ", name: "Mozambique", isd: "+258", flag: "🇲🇿" },
  { code: "ZM", name: "Zambia", isd: "+260", flag: "🇿🇲" },
  { code: "MG", name: "Madagascar", isd: "+261", flag: "🇲🇬" },
  { code: "RE", name: "Reunion", isd: "+262", flag: "🇷🇪" },
  { code: "ZW", name: "Zimbabwe", isd: "+263", flag: "🇿🇼" },
  { code: "NA", name: "Namibia", isd: "+264", flag: "🇳🇦" },
  { code: "MW", name: "Malawi", isd: "+265", flag: "🇲🇼" },
  { code: "LS", name: "Lesotho", isd: "+266", flag: "🇱🇸" },
  { code: "BW", name: "Botswana", isd: "+267", flag: "🇧🇼" },
  { code: "SZ", name: "Eswatini", isd: "+268", flag: "🇸🇿" },
  { code: "KM", name: "Comoros", isd: "+269", flag: "🇰🇲" },
  { code: "SH", name: "Saint Helena", isd: "+290", flag: "🇸🇭" },
  { code: "ER", name: "Eritrea", isd: "+291", flag: "🇪🇷" },
  { code: "AW", name: "Aruba", isd: "+297", flag: "🇦🇼" },
  { code: "FO", name: "Faroe Islands", isd: "+298", flag: "🇫🇴" },
  { code: "GL", name: "Greenland", isd: "+299", flag: "🇬🇱" },
  { code: "GI", name: "Gibraltar", isd: "+350", flag: "🇬🇮" },
  { code: "PT", name: "Portugal", isd: "+351", flag: "🇵🇹" },
  { code: "LU", name: "Luxembourg", isd: "+352", flag: "🇱🇺" },
  { code: "IE", name: "Ireland", isd: "+353", flag: "🇮🇪" },
  { code: "IS", name: "Iceland", isd: "+354", flag: "🇮🇸" },
  { code: "AL", name: "Albania", isd: "+355", flag: "🇦🇱" },
  { code: "MT", name: "Malta", isd: "+356", flag: "🇲🇹" },
  { code: "CY", name: "Cyprus", isd: "+357", flag: "🇨🇾" },
  { code: "FI", name: "Finland", isd: "+358", flag: "🇫🇮" },
  { code: "BG", name: "Bulgaria", isd: "+359", flag: "🇧🇬" },
  { code: "LT", name: "Lithuania", isd: "+370", flag: "🇱🇹" },
  { code: "LV", name: "Latvia", isd: "+371", flag: "🇱🇻" },
  { code: "EE", name: "Estonia", isd: "+372", flag: "🇪🇪" },
  { code: "MD", name: "Moldova", isd: "+373", flag: "🇲🇩" },
  { code: "AM", name: "Armenia", isd: "+374", flag: "🇦🇲" },
  { code: "BY", name: "Belarus", isd: "+375", flag: "🇧🇾" },
  { code: "AD", name: "Andorra", isd: "+376", flag: "🇦🇩" },
  { code: "MC", name: "Monaco", isd: "+377", flag: "🇲🇨" },
  { code: "SM", name: "San Marino", isd: "+378", flag: "🇸🇲" },
  { code: "UA", name: "Ukraine", isd: "+380", flag: "🇺🇦" },
  { code: "RS", name: "Serbia", isd: "+381", flag: "🇷🇸" },
  { code: "ME", name: "Montenegro", isd: "+382", flag: "🇲🇪" },
  { code: "XK", name: "Kosovo", isd: "+383", flag: "🇽🇰" },
  { code: "HR", name: "Croatia", isd: "+385", flag: "🇭🇷" },
  { code: "SI", name: "Slovenia", isd: "+386", flag: "🇸🇮" },
  { code: "BA", name: "Bosnia and Herzegovina", isd: "+387", flag: "🇧🇦" },
  { code: "MK", name: "North Macedonia", isd: "+389", flag: "🇲🇰" },
  { code: "CZ", name: "Czech Republic", isd: "+420", flag: "🇨🇿" },
  { code: "SK", name: "Slovakia", isd: "+421", flag: "🇸🇰" },
  { code: "LI", name: "Liechtenstein", isd: "+423", flag: "🇱🇮" },
  { code: "FK", name: "Falkland Islands", isd: "+500", flag: "🇫🇰" },
  { code: "BZ", name: "Belize", isd: "+501", flag: "🇧🇿" },
  { code: "GT", name: "Guatemala", isd: "+502", flag: "🇬🇹" },
  { code: "SV", name: "El Salvador", isd: "+503", flag: "🇸🇻" },
  { code: "HN", name: "Honduras", isd: "+504", flag: "🇭🇳" },
  { code: "NI", name: "Nicaragua", isd: "+505", flag: "🇳🇮" },
  { code: "CR", name: "Costa Rica", isd: "+506", flag: "🇨🇷" },
  { code: "PA", name: "Panama", isd: "+507", flag: "🇵🇦" },
  { code: "PM", name: "Saint Pierre and Miquelon", isd: "+508", flag: "🇵🇲" },
  { code: "HT", name: "Haiti", isd: "+509", flag: "🇭🇹" },
  { code: "GP", name: "Guadeloupe", isd: "+590", flag: "🇬🇵" },
  { code: "BO", name: "Bolivia", isd: "+591", flag: "🇧🇴" },
  { code: "GY", name: "Guyana", isd: "+592", flag: "🇬🇾" },
  { code: "EC", name: "Ecuador", isd: "+593", flag: "🇪🇨" },
  { code: "GF", name: "French Guiana", isd: "+594", flag: "🇬🇫" },
  { code: "PY", name: "Paraguay", isd: "+595", flag: "🇵🇾" },
  { code: "MQ", name: "Martinique", isd: "+596", flag: "🇲🇶" },
  { code: "SR", name: "Suriname", isd: "+597", flag: "🇸🇷" },
  { code: "UY", name: "Uruguay", isd: "+598", flag: "🇺🇾" },
  { code: "CW", name: "Curacao", isd: "+599", flag: "🇨🇼" },
  { code: "TL", name: "Timor-Leste", isd: "+670", flag: "🇹🇱" },
  { code: "NF", name: "Norfolk Island", isd: "+672", flag: "🇳🇫" },
  { code: "BN", name: "Brunei", isd: "+673", flag: "🇧🇳" },
  { code: "NR", name: "Nauru", isd: "+674", flag: "🇳🇷" },
  { code: "PG", name: "Papua New Guinea", isd: "+675", flag: "🇵🇬" },
  { code: "TO", name: "Tonga", isd: "+676", flag: "🇹🇴" },
  { code: "SB", name: "Solomon Islands", isd: "+677", flag: "🇸🇧" },
  { code: "VU", name: "Vanuatu", isd: "+678", flag: "🇻🇺" },
  { code: "FJ", name: "Fiji", isd: "+679", flag: "🇫🇯" },
  { code: "PW", name: "Palau", isd: "+680", flag: "🇵🇼" },
  { code: "WF", name: "Wallis and Futuna", isd: "+681", flag: "🇼🇫" },
  { code: "CK", name: "Cook Islands", isd: "+682", flag: "🇨🇰" },
  { code: "NU", name: "Niue", isd: "+683", flag: "🇳🇺" },
  { code: "WS", name: "Samoa", isd: "+685", flag: "🇼🇸" },
  { code: "KI", name: "Kiribati", isd: "+686", flag: "🇰🇮" },
  { code: "NC", name: "New Caledonia", isd: "+687", flag: "🇳🇨" },
  { code: "TV", name: "Tuvalu", isd: "+688", flag: "🇹🇻" },
  { code: "PF", name: "French Polynesia", isd: "+689", flag: "🇵🇫" },
  { code: "TK", name: "Tokelau", isd: "+690", flag: "🇹🇰" },
  { code: "FM", name: "Micronesia", isd: "+691", flag: "🇫🇲" },
  { code: "MH", name: "Marshall Islands", isd: "+692", flag: "🇲🇭" },
  { code: "KP", name: "North Korea", isd: "+850", flag: "🇰🇵" },
  { code: "HK", name: "Hong Kong", isd: "+852", flag: "🇭🇰" },
  { code: "MO", name: "Macau", isd: "+853", flag: "🇲🇴" },
  { code: "KH", name: "Cambodia", isd: "+855", flag: "🇰🇭" },
  { code: "LA", name: "Laos", isd: "+856", flag: "🇱🇦" },
  { code: "BD", name: "Bangladesh", isd: "+880", flag: "🇧🇩" },
  { code: "TW", name: "Taiwan", isd: "+886", flag: "🇹🇼" },
  { code: "MV", name: "Maldives", isd: "+960", flag: "🇲🇻" },
  { code: "LB", name: "Lebanon", isd: "+961", flag: "🇱🇧" },
  { code: "JO", name: "Jordan", isd: "+962", flag: "🇯🇴" },
  { code: "SY", name: "Syria", isd: "+963", flag: "🇸🇾" },
  { code: "IQ", name: "Iraq", isd: "+964", flag: "🇮🇶" },
  { code: "KW", name: "Kuwait", isd: "+965", flag: "🇰🇼" },
  { code: "SA", name: "Saudi Arabia", isd: "+966", flag: "🇸🇦" },
  { code: "YE", name: "Yemen", isd: "+967", flag: "🇾🇪" },
  { code: "OM", name: "Oman", isd: "+968", flag: "🇴🇲" },
  { code: "PS", name: "Palestine", isd: "+970", flag: "🇵🇸" },
  { code: "AE", name: "United Arab Emirates", isd: "+971", flag: "🇦🇪" },
  { code: "IL", name: "Israel", isd: "+972", flag: "🇮🇱" },
  { code: "BH", name: "Bahrain", isd: "+973", flag: "🇧🇭" },
  { code: "QA", name: "Qatar", isd: "+974", flag: "🇶🇦" },
  { code: "BT", name: "Bhutan", isd: "+975", flag: "🇧🇹" },
  { code: "MN", name: "Mongolia", isd: "+976", flag: "🇲🇳" },
  { code: "NP", name: "Nepal", isd: "+977", flag: "🇳🇵" },
  { code: "TJ", name: "Tajikistan", isd: "+992", flag: "🇹🇯" },
  { code: "TM", name: "Turkmenistan", isd: "+993", flag: "🇹🇲" },
  { code: "AZ", name: "Azerbaijan", isd: "+994", flag: "🇦🇿" },
  { code: "GE", name: "Georgia", isd: "+995", flag: "🇬🇪" },
  { code: "KG", name: "Kyrgyzstan", isd: "+996", flag: "🇰🇬" },
  { code: "UZ", name: "Uzbekistan", isd: "+998", flag: "🇺🇿" },
  { code: "BS", name: "Bahamas", isd: "+1242", flag: "🇧🇸" },
  { code: "BB", name: "Barbados", isd: "+1246", flag: "🇧🇧" },
  { code: "AI", name: "Anguilla", isd: "+1264", flag: "🇦🇮" },
  { code: "AG", name: "Antigua and Barbuda", isd: "+1268", flag: "🇦🇬" },
  { code: "VG", name: "British Virgin Islands", isd: "+1284", flag: "🇻🇬" },
  { code: "VI", name: "US Virgin Islands", isd: "+1340", flag: "🇻🇮" },
  { code: "KY", name: "Cayman Islands", isd: "+1345", flag: "🇰🇾" },
  { code: "BM", name: "Bermuda", isd: "+1441", flag: "🇧🇲" },
  { code: "GD", name: "Grenada", isd: "+1473", flag: "🇬🇩" },
  { code: "TC", name: "Turks and Caicos Islands", isd: "+1649", flag: "🇹🇨" },
  { code: "MS", name: "Montserrat", isd: "+1664", flag: "🇲🇸" },
  { code: "MP", name: "Northern Mariana Islands", isd: "+1670", flag: "🇲🇵" },
  { code: "GU", name: "Guam", isd: "+1671", flag: "🇬🇺" },
  { code: "AS", name: "American Samoa", isd: "+1684", flag: "🇦🇸" },
  { code: "SX", name: "Sint Maarten", isd: "+1721", flag: "🇸🇽" },
  { code: "LC", name: "Saint Lucia", isd: "+1758", flag: "🇱🇨" },
  { code: "DM", name: "Dominica", isd: "+1767", flag: "🇩🇲" },
  { code: "VC", name: "Saint Vincent and the Grenadines", isd: "+1784", flag: "🇻🇨" },
  { code: "PR", name: "Puerto Rico", isd: "+1787", flag: "🇵🇷" },
  { code: "DO", name: "Dominican Republic", isd: "+1809", flag: "🇩🇴" },
  { code: "TT", name: "Trinidad and Tobago", isd: "+1868", flag: "🇹🇹" },
  { code: "KN", name: "Saint Kitts and Nevis", isd: "+1869", flag: "🇰🇳" },
  { code: "JM", name: "Jamaica", isd: "+1876", flag: "🇯🇲" },
  { code: "RU", name: "Russia", isd: "+7", flag: "🇷🇺" },
  { code: "KZ", name: "Kazakhstan", isd: "+7", flag: "🇰🇿" },
].sort((a, b) => {
  // Sort by ISD code numerically
  const isdA = parseInt(a.isd.replace('+', ''));
  const isdB = parseInt(b.isd.replace('+', ''));
  return isdA - isdB;
});

// Get unique ISD codes for dropdown (some countries share codes)
export const getCountriesSortedByISD = () => ALL_COUNTRIES;

// Search function for filtering countries
export const searchCountries = (query: string): CountryData[] => {
  if (!query.trim()) return ALL_COUNTRIES;
  
  const searchTerm = query.toLowerCase().trim();
  return ALL_COUNTRIES.filter(country => 
    country.name.toLowerCase().includes(searchTerm) ||
    country.isd.includes(searchTerm) ||
    country.code.toLowerCase().includes(searchTerm)
  );
};
